### ISSUE TITLE
allow DSpace Collection URIs to resolve to SOLR query in Hyrax

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1015]
use the DSpace_Collection metadata field to fire off a query for items in that DSpace_Collection. Redirect DSpace Collection handles to those queries.

**Comment by luisgreg99** [comment]
Our plan to handle the redirects for collection handles:

- [ ] 1. Merge PR https://github.com/osulp/Scholars-Archive/pull/1020
- [ ] 2. Deploy to production
- [ ] 3. Run `RAILS_ENV=production bundle exec rake scholars_archive: reindex_everything`
- [ ] 4. Update https://github.com/osulp/Scholars-Archive/blob/master/config/handles_ir_collections.yml so that the destination will be the catalog search in the form 

`http://ir.library.oregonstate.edu/catalog?q=hello+world&search_field=dspace_collection`
