### ISSUE TITLE
OD handles should redirect to OD and nowhere else

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1021]
OD handles should never redirect to SA@OSU

**Comment by luisgreg99** [comment]
@vantuyls it looks like this issue has been fixed by these PRs: 
- https://github.com/osulp/Scholars-Archive/pull/1058
- https://github.com/osulp/Scholars-Archive/pull/1046 
- https://github.com/osulp/Scholars-Archive/pull/1038

I think we can close this one unless you know a particular OD handle that isn't working or is redirecting to SA@OSU instead?
