### ISSUE TITLE
Deposits to Datasets (and maybe other types) are duplicating notification messages (in system) and emails

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1079]
both "awaiting approval"

and

"awaiting review"

**Comment by luisgreg99** [comment]
It turns out that there were old workflow notification objects still being active in the database that were intended to be replaced with new objects in this pr https://github.com/osulp/Scholars-Archive/pull/740

The notifications in the database was:
```
Sipity::Notification.all.map { |n| n.name }
=> ["Hyrax::Workflow::PendingReviewNotification",
"Hyrax::Workflow::ChangesRequiredNotification",
"Hyrax::Workflow::DepositedNotification",
"ScholarsArchive::Workflow::PendingReviewNotification",  "ScholarsArchive::Workflow::DepositReceivedNotification", 
"ScholarsArchive::Workflow::ChangesRequiredNotification", 
"ScholarsArchive::Workflow::DepositedNotification"]
 ```

`"Hyrax::Workflow::PendingReviewNotification", "Hyrax::Workflow::ChangesRequiredNotification", "Hyrax::Workflow::DepositedNotification"` were intended to be replaced with `"ScholarsArchive::Workflow::PendingReviewNotification ","ScholarsArchive::Workflow::ChangesRequiredNotification", "ScholarsArchive::Workflow::DepositedNotification"`

Removed the old records from the database, and now the query returns the expected list:

```
Sipity::Notification.all.map { |n| n.name }
=> ["ScholarsArchive::Workflow::PendingReviewNotification", 
"ScholarsArchive::Workflow::DepositReceivedNotification", 
"ScholarsArchive::Workflow::ChangesRequiredNotification", 
"ScholarsArchive::Workflow::DepositedNotification"]
```

When loading a notification object with `bundle exec rake hyrax:workflow:load` the task seems to create objects on new notification names, so it doesn't replace the object if the name gets changed.
