### ISSUE TITLE
Allow non-ONID users to login and deposit content

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1120]
for Easy Deposit 2 and other projects, we need to allow non-OSU users to log into the system to deposit content.

**Comment by revgum** [comment]
A good idea might be to issue an "Invitation" to register with SA, so that users on the Internet aren't able to register at will.

**Comment by revgum** [comment]
Also..instead of defaulting to "CAS" login, we could render an interstitial that allows the user to decide to login using OSU authentication or by email address.

*However* we shouldn't allow a user to login using email address if they are registered as a type of user having come from CAS originally. (Even though they have an email address in the Users table)

**Comment by vantuyls** [comment]
@zhang4952 we're still going to need this for ED2. Do you have a relevant issue on that repo that you can link to this one?

**Comment by revgum** [comment]
This is no longer valid, as ED2 is a separate application and uses an HTTP API authentication to publish works on the behalf of users. PR #1448 addresses the authentication piece and https://github.com/osulp/Easydeposit2 is the application
