### ISSUE TITLE
loading the dashboard is unacceptably slow

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1137]
from the user name link in the top right of the page, select dashboard...load time is slow

**Comment by wickr** [comment]
Related to #1135

**Comment by straleyb** [comment]
@simholt 

I can fix this but it may include running a weekly script to delete old notifications. If I were to delete old notifications, how long would we want to keep notifications around before they were removed? 

Otherwise, I could also remove the count, and instead just check to see if there are notifications. Then change the color of the icon to just show that there are unread notifications.

3rd would just be to not show the new notifications. 

The first solution would be a solution to fix the long loading times for the notification page too.

**Comment by simholt** [comment]
@straleyb I talked to Margaret and we think leaving things as they are is okay for now. Closing.
