### ISSUE TITLE
change Honors College notification emails

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1189]
the emails are currently making mention of the Graduate School rather than the Honors College. We need to correct the messages to ensure we don't confuse depositors from the Honors College.

**Comment by wickr** [comment]
I started looking at this and nothing is jumping out at me as being misconfigured. I looked at the workflows and the email notifications. Possibly there's workflow settings I can't see on production. Or maybe one of the user keys getting retrieved for an item is incorrect.

Do you have a specific example of the email?

**Comment by simholt** [comment]
No specific example; I got a message from Bailey: 

> We had our first thesis submission of the term. He didn’t have any trouble uploading it but mention getting an email that said something about Graduate School review.

**Comment by vantuyls** [comment]
@luisgreg99 can you point us a the location of those workflow email notifications? are they in the workflow.json or somewhere else?

**Comment by luisgreg99** [comment]
@vantuyls @wickr yes, we can change the workflow if we go to the edit admin set form: `Dashboard -> Admin Sets -> Honors College Theses -> Edit -> Workflow tab`. 

It looks like the `Honors College Theses` admin set is still configured to use the `Graduate Thesis and Dissertation Workflow`. 

I noticed that Steve added a new workflow for Honors College Theses https://github.com/osulp/Scholars-Archive/blob/master/config/workflows/honorscollege.json, but it looks like it still needs to be loaded on the server because it's not available in the options (Workflow tab) yet when editing an admin set.

To load the new workflow, we can do:
```
RAILS_ENV=production bundle exec rake hyrax:workflow:load
```

Once the rake task is done, the new workflow should become available in the form under the `Workflow` tab. I think there is an admin set for Honors College Theses on staging, so we can also test it there to double check that honorscollege.json works as expected.

**Comment by wickr** [comment]
@luisgreg99 great, I'll test loading the Honors College workflow on staging.

**Comment by vantuyls** [comment]
@luisgreg99 where is the text of the notifications stored, though?

**Comment by wickr** [comment]
@vantuyls https://github.com/osulp/Scholars-Archive/blob/master/app/services/scholars_archive/workflow/changes_required_notification.rb
(also Email Notifications tab in MAP has them linked). I looked through them and nothing is hard-coded.

**Comment by luisgreg99** [comment]
@vantuyls the text in the email subject and body (message) is dynamically generated based on these templates https://github.com/osulp/Scholars-Archive/tree/master/app/services/scholars_archive/workflow the workflow configuration files https://github.com/osulp/Scholars-Archive/tree/master/config/workflows specify which of the notification object(s) are used depending on the state of the workflow

**Comment by wickr** [comment]
@vantuyls @simholt Honors College Thesis Workflow is set for Honors College Thesis admin set on production.

**Comment by wickr** [comment]
Closing this as completed, with the loading of HC workflow on production and setting the admin set to use it.
