### ISSUE TITLE
Embargo release cron is not functioning properly.

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1254]
Expired embargoes are not being released. 

Likely cause:
https://github.com/osulp/Scholars-Archive/blob/master/lib/scholars_archive/embargoes/embargo_releaser.rb#L19

Could use `Hyrax::EmbargoService.assets_with_expired_embargoes` instead?

**Comment by revgum** [comment]
When reworking this method, `destroy` on the embargo actor fails with:

```
irb(main):012:0> a = Hyrax::Actors::EmbargoActor.new(work)
irb(main):012:0> a.destroy
NoMethodError: undefined method `empty?' for nil:NilClass
	from /data0/hydra/releases/20180221002443/lib/scholars_archive/validators/graduation_year_validator.rb:4:in `validate'
```

**Comment by revgum** [comment]
Fixed using:
```
work.embargo_visibility!
work.deactive_embargo!
work.embargo.save!
work.save!(validate: false)
```

**Comment by luisgreg99** [comment]
I got into a similar issue with my script recently. My workaround was to set `work.graduation_year = ""` to proceed. I think it would be a good idea to update the graduation_year validator to check for nil values as well in addition to empty values: https://github.com/osulp/Scholars-Archive/blob/master/lib/scholars_archive/validators/graduation_year_validator.rb#L4 I think we can do `record.graduation_year.present?` instead of `record.graduation_year.empty?`

**Comment by revgum** [comment]
@luisgreg99 great call on using `.present?` ... or even `.blank?` would work as well.
