### ISSUE TITLE
SA uploads losing file and/or allowing deposit without file

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1383]
This happened once last week (did not record) and twice today:

Student uploaded file but it isn't showing on the record:
https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/sf268b14h

This submission came through without a file:
https://ir.library.oregonstate.edu/concern/undergraduate_thesis_or_projects/8p58pk39f

@luisgreg99 Pulled up full log message: https://osulets.slack.com/archives/C03G2FZ9Q/p1525470332000363

**Comment by luisgreg99** [comment]
I took a closer look at the sidekiq logs and was able to reproduce the error  `NoMethodError: undefined method title' for nil:NilClass`. The bug is happening when a user selects an `Other` entry for one of the multi-value fields (degree_field and/or degree_name) and leaves it blank. The fix in https://github.com/osulp/Scholars-Archive/pull/1384 addresses this case.
