### ISSUE TITLE
Cannot call create on existing work

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1437]
When there is a failed ingest (only in a specific part of the save), the work makes it onto fedora, but nowhere else. The next time an item is ingested, that old work gets sent along with the new work and ends up getting create called on it again. This is causing the error.

Possible remedies:
One way the item has been fixed is by creating a break point in the `NestedFieldsOperationsActor` and calling `next_actor.create(env)` on it. This throws the error, but then after you continue past the break point, it flushes that work out and fixes it. 

Possibly find that work in fedora and nuke it? How do we locate the work?

**Comment by straleyb** [comment]
went in and deleted the work from the all works list from the dashboard. Possibly have to kick the application and restart it after deleting it to ensure it flows through.

**Comment by straleyb** [comment]
This is currently being worked on in hyrax https://github.com/samvera/hyrax/issues/3128

**Comment by revgum** [comment]
This happens when some validation fails in the ActorStack but the work was partially persisted causing the minter to get out of state. This tends to not happen on Production or Staging. The workaround is to open the console and force the minter to a new state:

`[::Noid::Rails::Service.new.minter.mint, ::Noid::Rails::Service.new.minter.mint]`
