### ISSUE TITLE
[Advanced Search] 1 Item found but not showing in search results.

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1476]

**Comment by wickr** [comment]
This is because the page value is being retained from any prior browsing.

Steps to reproduce:

1. browse past page 1 of all results, such as: http://ir-staging.library.oregonstate.edu/catalog?locale=en&page=4&q=&search_field=all_fields   (page 4)
2. click Advanced Search
3. select facets or search terms to get a small number of results, click Search
4. correct count is returned, but the page value tries to jump ahead to nonexistent records, and a blank space is shown instead of results
