### ISSUE TITLE
Embargoes are not expiring

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1488]
We are still not seeing all (any?) embargoes automatically expiring. Example here:
http://ir.library.oregonstate.edu/concern/honors_college_theses/fb494b287

this was manually expired by @simholt when it had not expired automatically.

**Comment by zhang4952** [comment]
"embargo_history_ssim":["An active embargo was deactivated on 2018-06-05.  Its release date was 2018-06-05T00:00:00+00:00.  Visibility during embargo was restricted and intended visibility after embargo was authenticated"]

**Comment by simholt** [comment]
Clara brought this one to my attention:
http://ir.library.oregonstate.edu/concern/datasets/3484zm97d 

Same story as above item -- embargo expired fine in dspace but item is private in Hyrax. I set it to public manually.

**Comment by vantuyls** [comment]
@zhang4952 can you give us an update on this embargo expiration issue?

**Comment by straleyb** [comment]
So it seems like the issue lies in the embargo expiring mechanism. Some are expiring properly and some are not expiring properly. Specifically, the ones expiring improperly are expiring to the wrong visibility. This could be an issue with the data that is stored in the embargo object maybe only on migrated items from dspace.

**Comment by straleyb** [comment]
Inspecting objects, the issue could potentially be that the actual embargo objects associated with works didn't get created. A good beginning course of action would be to aggregate all the works with expired embargoes from dspace and see if their equivalent objects in SA have some sort of embargo object.

**Comment by straleyb** [comment]
#<Hydra::AccessControls::Embargo id: "d4a52792-e91b-4997-b029-922f5ab64493", visibility_during_embargo: nil, visibility_after_embargo: nil, embargo_release_date: nil, embargo_history: ["An active embargo was deactivated on 2018-07-04.  Its release date was 2018-07-04T00:00:00+00:00.  Visibility during embargo was restricted and intended visibility after embargo was open"]>
irb(main):025:0> w.embargo
=> #<Hydra::AccessControls::Embargo id: "ea1df734-db13-4452-8708-37fe5a36a043", visibility_during_embargo: "restricted", visibility_after_embargo: "open", embargo_release_date: "2018-08-01 00:00:00", embargo_history: []>

Top one expired wrong, but the second one should expire 8/1/2018

**Comment by vantuyls** [comment]
@straleyb can you drop some more status updates here? i'm curious about where we stand on this issue.

**Comment by straleyb** [comment]
Havent heard of any issues with the embargoes not expiring anymore. Need some feedback from @vantuyls @simholt if we can close this issue.

**Comment by simholt** [comment]
@straleyb @zhang4952 

Here's a migrated one that did not expire in February 2019 like it was supposed to:
 https://ir.library.oregonstate.edu/concern/articles/nk322f993 

This is another example like the two listed above -- expired in dspace but not Hyrax.

**Comment by simholt** [comment]
Here's a list of 19 migrated embargoes that wrongly expired to Private visibility:

https://ir.library.oregonstate.edu/concern/defaults/9019s752t
https://ir.library.oregonstate.edu/concern/defaults/gf06g759r
https://ir.library.oregonstate.edu/concern/defaults/9g54xp68s
https://ir.library.oregonstate.edu/concern/defaults/cn69m594z
https://ir.library.oregonstate.edu/concern/defaults/x920g018m
https://ir.library.oregonstate.edu/concern/defaults/z316q668m
https://ir.library.oregonstate.edu/concern/defaults/0g354j530
https://ir.library.oregonstate.edu/concern/defaults/mk61rn91q
https://ir.library.oregonstate.edu/concern/defaults/pr76f830c
https://ir.library.oregonstate.edu/concern/defaults/nk322f993
https://ir.library.oregonstate.edu/concern/defaults/hm50tv96d
https://ir.library.oregonstate.edu/concern/defaults/8g84mr75b
https://ir.library.oregonstate.edu/concern/defaults/qn59q585r
https://ir.library.oregonstate.edu/concern/defaults/br86b700p
https://ir.library.oregonstate.edu/concern/defaults/0k225h21c
https://ir.library.oregonstate.edu/concern/defaults/d791sj95s
https://ir.library.oregonstate.edu/concern/defaults/rf55zb81z
https://ir.library.oregonstate.edu/concern/defaults/vx021m058
https://ir.library.oregonstate.edu/concern/defaults/9z9034243

**Comment by simholt** [comment]
Test cases:
Migrated embargoes to watch:
https://ir.library.oregonstate.edu/concern/defaults/70795d88p
Under embargo. Is still restricted in DSpace. Has embargo reason listed. Supposed to expire 2019-11-27.

https://ir.library.oregonstate.edu/concern/defaults/wm117v19g
Under embargo. Is still restricted in DSpace. Has embargo reason listed. Supposed to expire 2019-11-27.

https://ir.library.oregonstate.edu/concern/articles/m613n024d
Under embargo. Is still restricted in DSpace. No embargo information on SA page. Supposed to expire 2019-12-02.

**Comment by straleyb** [comment]
@simholt So I looked through the list of the embargoes per the email. They all basically seemed to fail in the same way.  Except for one.

https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/9z9034243?locale=en
This is the only one that seems to not make sense compared to the others. 

This is because the embargo information suggests `An active embargo was deactivated on 2019-05-06. Its release date was 2019-06-12T00:00:00+00:00. Visibility during embargo was restricted and intended visibility after embargo was open`

This work could have had issues because it was deactivated early so I think we could talk more about the above work. 

```
2019-04-30
2019-04-21
2019-04-13
2019-04-21
2019-04-08
2019-03-21
2019-03-14
2019-03-02
2019-02-21
2019-02-05
2019-01-14
2019-01-11
```
Above are all the dates of the other embargoes that had elapsed improperly from the list provided in email. These works all released on the day they said, but didn't release. Their embargo reasons all show that they expired on the proper date however. For example, the `GraduateThesisOrDissertation` with the id `mk61rn91q` expired with the message `An active embargo was deactivated on 2019-01-14.  Its release date was 2019-01-14T00:00:00+00:00.  Visibility during embargo was restricted and intended visibility after embargo was open`

The only thing I can see is that there was an update on May 6th found here
https://github.com/osulp/Scholars-Archive/commit/09c1afb4acd384366f33346d80aba4a425679fec#diff-5e6b78a6ac54286f56eb922b90aa57fd
which fixed an issue found here https://github.com/osulp/Scholars-Archive/issues/1857

The last big update before that to the mechanism that expires the embargoes was from July 2018 which is well before these. So all the other works didn't expire properly for presumably the same reason. Which is currently unknown. Ill continue to dig into these and see what I can find. These are just my initial findings.

**Comment by straleyb** [comment]
```
#<Hydra::AccessControls::Embargo id: "c6a0485e-f491-48ae-a711-fcddcbc2441c", visibility_during_embargo: "restricted", visibility_after_embargo: "open", embargo_release_date: "2019-11-27 00:00:00", embargo_history: []>
```
```
=> #<Hydra::AccessControls::Embargo id: "15ae82d6-8d81-4520-b278-0274db9d7bb1", visibility_during_embargo: "restricted", visibility_after_embargo: "open", embargo_release_date: "2019-11-09 00:00:00", embargo_history: []>
```
Here are two embargoes that are essencially the same. The top one is a migrated work and the bottom is a normally ingested work. Seems like all the embargo info is set properly. 

```
#<Hydra::AccessControls::Embargo id: "5782af6c-0625-4f2a-80a2-efc6070c6d2f", visibility_during_embargo: "restricted", visibility_after_embargo: "open", embargo_release_date: "2019-11-27 00:00:00", embargo_history: []>
```
```
#<Hydra::AccessControls::Embargo id: "2c91fbc6-ec68-450c-80d8-1547be52d0bf", visibility_during_embargo: "restricted", visibility_after_embargo: "open", embargo_release_date: "2019-12-02 00:00:00", embargo_history: []>
```
These are the other two migrated embargoes. 

https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/fn107433f?locale=en
This is an embargo that is set to expire over the weekend and does not have an embargo reason.

**Comment by simholt** [comment]
@straleyb When was the embargo rake task started?

**Comment by simholt** [comment]
I set the 19 ones that went to private to appropriate visibility today.

**Comment by straleyb** [comment]
@simholt Those migrated works posted as test cases seem to have expired properly. I checked all their embargo info at it seems to line up.
