### ISSUE TITLE
Restrict Degree Name based on Degree Level for depositors

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1493]
For depositors, when a Degree Name is selected, they should only see Degree Levels that correspond to the Degree Name.

Degree Name should be "smart" based on what Degree Level is selected.

Level: Bachelor
Name:
- Bachelor of Science (B.S.)
- Bachelor of Arts (B.A.)
- Honors Bachelor of Arts (H.B.A.)
- Honors Bachelor of Fine Arts (H.B.F.A.)
- Honors Bachelor of Science (H.B.S.)

Level: Masters
Name: 
- Master of Agriculture (M.Ag.)
- Master of Arts (M.A.)
- Master of Arts in Interdisciplinary Studies (M.A.I.S.)
- Master of Business Administration (M.B.A.)
- Master of Education (Ed.M.)
- Master of Fine Arts (M.F.A.)
- Master of Ocean Engineering (M.Oc.E. )
- Master of Public Health (M.P.H.)
- Master of Science (M.S.)

Level: Doctoral
Name: 
- Doctor of Philosophy (Ph.D.)
- Doctor of Education (Ed.D.)

**Comment by simholt** [comment]
This ticket needs to be brought up to date. The degree names are not current.

**Comment by simholt** [comment]
@lamtu1 Okay! -- the new degree names (that were not listed in original ticket) are in BOLD. Having "Other" still be an option may lead to user error but it also helps us discover new programs and redirecting students.

Degree Level: Bachelor
Degree name options:
- Bachelor of Arts (B.A.) 
- **Bachelor of Fine Arts (B.F.A.)**
- Bachelor of Science (B.S.)
- Honors Bachelor of Arts (H.B.A.)
- Honors Bachelor of Fine Arts (H.B.F.A.)
- Honors Bachelor of Science (H.B.S.)
- **Other**

Degree Level: Masters
Degree name options:
- **Executive Master of Public Policy (E.M.P.P.)**
- Master of Agriculture (M.Ag.)
- Master of Arts (M.A.)
- Master of Arts in Interdisciplinary Studies (M.A.I.S.)
- Master of Business Administration (M.B.A.)
- Master of Education (Ed.M.)
- Master of Fine Arts (M.F.A.)
- **Master of Forestry (M.F.)**
- **Master of Natural Resources (M.N.R.)**
- Master of Ocean Engineering (M.Oc.E. )
- Master of Public Health (M.P.H.)
- **Master of Public Policy (M.P.P.)**
- Master of Science (M.S.)
- **Professional Science Masters (P.S.M.)**
- **Other**

Level: Doctoral
Degree name options:
- Doctor of Education (Ed.D.)
- Doctor of Philosophy (Ph.D.)
- **Other**

**Comment by simholt** [comment]
@lamtu1 
Overall, looks good! Thanks for adding DVM to Doctoral -- it technically *isn't* a Doctoral program but I'm not sure how else we can represent it here.
Only weirdness I noticed was for the Honors College Thesis worktype. That one is set up to have the **Bachelors** Degree Level default already because only undergrad students submit HCT. When I went to choose a degree name, all the options are there. To get *just* the Bachelor options, I have to click another Degree Level and then select Bachelors again.

<img width="340" alt="Screenshot 2023-09-07 at 11 51 53 AM" src="https://github.com/osulp/Scholars-Archive/assets/33705514/2c869725-37d3-41ba-9352-1e7f026cd4f2">

**Comment by lamtu1** [comment]
@simholt That is an edge case I didn't have a look at. I will go back in to check all the other works and make sure they will display it correctly

**Comment by Jake-Marley** [comment]
:rattle rattle:

**Comment by simholt** [comment]
QA pass! All good here --
