### ISSUE TITLE
Review other tokens

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#1509]
Authenticity token?

**Comment by revgum** [comment]
This token is necessary for CSRF protection. The security audit found this as a medium risk because Blacklight seems to pass any/all querystring params through to links that it renders. Blacklight "SearchState" manages adding/removing facets and other functionality so that all links it renders will include whatever previous search intents the user has selected. 

Further, authenticity_token is generated on each page render in conjunction with the session cookie which makes this finding less of a concern. On the other hand, it might be worthwhile getting this in front of the Blacklight community to consider improving SearchState.
