### ISSUE TITLE
For ordered works, old title value/predicate remain

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1706]
### Descriptive summary

Once a work has been changed to ordered, the old values are usually cleared out. The old Title predicate and value remain though.

```
<http://127.0.0.1:8080/fcrepo/rest/prod/cr/56/n1/72/cr56n172z> <http://purl.org/dc/terms/title> "Runoff generation in a steep, tropical montane cloud forest catchment on permeable volcanic substrate" .
<http://127.0.0.1:8080/fcrepo/rest/prod/cr/56/n1/72/cr56n172z> <http://purl.org/dc/elements/1.1/title> <http://127.0.0.1:8080/fcrepo/rest/prod/cr/56/n1/72/cr56n172z#nested_ordered_titleg47242808103260> .
<http://127.0.0.1:8080/fcrepo/rest/prod/cr/56/n1/72/cr56n172z#nested_ordered_titleg47242808103260> <http://purl.org/ontology/olo/core#index> "0" .
<http://127.0.0.1:8080/fcrepo/rest/prod/cr/56/n1/72/cr56n172z#nested_ordered_titleg47242808103260> <http://purl.org/dc/terms/title> "Runoff generation in a steep, tropical montane cloud forest catchment on permeable volcanic substrate" .

```

Creator, Contributor and Additional Information seem to be working as expected. I haven't inspected one with Abstract yet to make sure.

**Comment by simholt** [comment]
@CGillen Need help/instruction on QA for this one, also.

**Comment by CGillen** [comment]
Before:
```
> record = ActiveFedora::Base.find('vt150j424')
> orm = Ldp::Orm.new(record.ldp_source)
> orm.value RDF::Vocab::DC.title
=> [#<RDF::Literal:0x2af2860e871c("title 1")>, #<RDF::Literal:0x2af286109b24("title 3")>, #<RDF::Literal:0x2af2860f62f4("title 12")>
> orm.value RDF::Vocab::DC11.title
=> [#<RDF::URI:0x2af28b63385c URI:http://127.0.0.1:8080/fcrepo/rest/staging/vt/15/0j/42/vt150j424#nested_ordered_titleg47124452982940>, #<RDF::URI:0x2af28b609a20 URI:http://127.0.0.1:8080/fcrepo/rest/staging/vt/15/0j/42/vt150j424#nested_ordered_titleg47124445941320>]
```
After
```
> orm.value RDF::Vocab::DC.title
=> []
irb(main):004:0> orm.value RDF::Vocab::DC11.title
=> [#<RDF::URI:0x2aff4d7ae078 URI:http://127.0.0.1:8080/fcrepo/rest/staging/vt/15/0j/42/vt150j424#nested_ordered_titleg47124452982940>, #<RDF::URI:0x2aff4d7a5fcc URI:http://127.0.0.1:8080/fcrepo/rest/staging/vt/15/0j/42/vt150j424#nested_ordered_titleg47124445941320>]
```
Title is still in work show, edit, and metadata

After re-saving work:
```
> orm.value RDF::Vocab::DC.title
=> []
irb(main):009:0> orm.value RDF::Vocab::DC11.title
=> [#<RDF::URI:0x2aff49d0f6c4 URI:http://127.0.0.1:8080/fcrepo/rest/staging/vt/15/0j/42/vt150j424#nested_ordered_titleg47454741740660>, #<RDF::URI:0x2aff49d42c7c URI:http://127.0.0.1:8080/fcrepo/rest/staging/vt/15/0j/42/vt150j424#nested_ordered_titleg47454741859400>]
```

However, this work lost its titles https://ir-staging.library.oregonstate.edu/concern/articles/8336h2114
Without knowing if this work was properly migrated to nested titles before IDK if this is pass. I'm QA failing and suggesting we add a check for a nested title/abstract exists before deleting non-nested

**Comment by CGillen** [comment]
This ticket still needs the rake task run, but I don't feel fully comfortable running it without some kind of logging message for works that have to be skipped because they don't have ordered titles or abstracts yet.
This situation only occurred once on staging and resulted in #2206. Right now, if a work only has unordered metadata it's skipped but we should add some kind of log or summary of those works

**Comment by CGillen** [comment]
The job has finished running.

- 72315 works had their unordered title(s) removed
- 36431 works had their unordered abstract(s) removed
- 5 works skipped updating the title because they were missing an ordered title
  - 4x51hj529
  - 9p290987v
  - 5q47rp33g
  - ng451j359
  - 0g354f54n
- 5 works skipped updating the abstract because they were missing an ordered abstract
  - vd66w165n
  - c534fv18f
  - 6682x901h
  - c534ft75v
  - cz30ps84v
