### ISSUE TITLE
Migrated creators 10+ out of order

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1796]
### Descriptive summary
After ordered fields were established, it turned out that order was not maintained for non-migrated items of 10+ terms, such as Creator. ([#1773](https://github.com/osulp/Scholars-Archive/issues/1773))

It is a problem for migrated items as well.

9 is fine
https://ir.library.oregonstate.edu/concern/articles/02870w72j
http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/36332?show=full

As before, 10 creators is the magic number -- out of order
https://ir.library.oregonstate.edu/concern/articles/bn999744w
http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/42664?show=full

13 creators -- out of order
https://ir.library.oregonstate.edu/concern/defaults/xg94hv61v
http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/36591?show=full

ALSO: Order was not maintained for Contributor, but there was only one item with 10+ entries so I fixed it manually.

### Related work

[#1773](https://github.com/osulp/Scholars-Archive/issues/1773)

**Comment by simholt** [comment]
To make this more complicated, any name with diacritics in DSpace was brought into Hyrax twice -- once with unrecognized characters and again with proper diacritics.

![screen shot 2019-01-29 at 7 51 37 am](https://user-images.githubusercontent.com/33705514/51920672-baf40200-239a-11e9-8d98-d989c57392fe.png)
- - - 
This gives us two types of problems:

- Less than ten creators: the unrecognized character version is in the correct order and the diacritic one is kicked to the end of the list. Fixing this means deleting the wrong one. [Example](https://ir.library.oregonstate.edu/concern/articles/5138jg786)
![screen shot 2019-01-29 at 7 54 24 am](https://user-images.githubusercontent.com/33705514/51920887-2342e380-239b-11e9-8414-844629799689.png)

- Ten or more creators means the order is messed up in two ways: loss of order as listed in DSpace and duplication of names with diacritics. [Example](https://ir.library.oregonstate.edu/concern/articles/pv63g434h)

![screen shot 2019-01-29 at 8 00 35 am](https://user-images.githubusercontent.com/33705514/51921332-0a86fd80-239c-11e9-946b-5a2f886d6dcd.png)
- - - 
Other examples:
https://ir.library.oregonstate.edu/concern/articles/th83m1037
https://ir.library.oregonstate.edu/concern/articles/vt150k900

And this one is having a similar problem but there are no diacritics: https://ir.library.oregonstate.edu/concern/articles/nc580p14h

**Comment by luisgreg99** [comment]
@simholt @wickr I tried to make a Solr query to match all works where `replaces_tesim` is set and where `creator_tesim` count is greater than or equal to 10.

At first, I looked into filter queries `fq` in solr to see if we could make a custom filter for the count, but I found that it only supports filters for single value fields. 

Then I looked a bit deeper, and found that to calculate the count for a multi value field using solr queries, there is a processor function [CountFieldValuesUpdateProcessorFactory](http://lucene.apache.org/solr/4_0_0/solr-core/org/apache/solr/update/processor/CountFieldValuesUpdateProcessorFactory.html) that we could use. To set this up, we would need to update `solrconfig.xml`, add a new field (i.e. `creator_count`), then reindex everything to be able to query with something like `creator_count>9`.

I'm thinking that for this particular query, it would be better to make a rake task to do the custom filter for creator_count. So far, I have this query that returns all works where `replaces_tesim` is set.

```
creator_tesim:[* TO *] AND -has_model_ssim:FileSet AND replaces_tesim:[* TO *]
```

The rake task would start with this query, then it would do the filter based on the count, and finally send the list of ids to a csv file. I'm going to give this a try next, and see if we can get a list of ids that we can work with to fix the ordering.

**Comment by luisgreg99** [comment]
After debugging this [example](https://ir.library.oregonstate.edu/concern/articles/5138jg786) within my dev environment, I was able to recreate the steps to reproduce the issue with special characters:

1. Create a work of type `Article` with the following fields:
		a. Title: `Hola Mundo`
		b. Creator: `Zwolak, Justyna P.` and `Chruściński, Dariusz`
		c. Replaces: `http://hdl.handle.net/1957/49001`

2. Go to show page and check `Creator`:
![image](https://user-images.githubusercontent.com/3486120/53637152-44cffe80-3bd7-11e9-9289-18e8d5def8ee.png)

3. Create a csv with filename `/data/tmp/dspace_creator_order_wrong_symbols.csv`, and add the following content (I extracted it from `ordered_attributes_migrations/dspace_creator_order.csv` in the server, and it applies only to handle `1957/49001`):

![image](https://user-images.githubusercontent.com/3486120/53637449-0850d280-3bd8-11e9-9c1a-0a3ebb2d8876.png)


4. Open rails console `bundle exec rails c` and run these commands
```
creator_csv_path = '/data/tmp/dspace_creator_order_wrong_symbols.csv'

migrator = ScholarsArchive::MigrateOrderedMetadataService.new(creator_csv_path:creator_csv_path,title_csv_path:'tmp/title_migration.csv',contributor_csv_path:'tmp/contributor_migration.csv')

w = ActiveFedora::Base.find("nv9352841")

handle = "1957/49001"

doc = migrator.solr_doc(handle, w)

creators = migrator.creators(handle, doc)

w.nested_ordered_creator = []
w.nested_ordered_creator_attributes = creators
w.save!
```

5. Inspect show page:
![image](https://user-images.githubusercontent.com/3486120/53637207-6af59e80-3bd7-11e9-8718-b5d97bc0aa0d.png)

**Comment by luisgreg99** [comment]
**Next Steps**

I think it would be better to cleanup the original ordered metadata CSV, then run again the order migration. Here's my checklist with possible steps:

- [ ] 1. Cleanup `/data0/hydra/shared/ordered_attributes_migrations/dspace_creator_order.csv`: grep wrong chars and replace them with the expected ones from bags (it might be better to rebuild this CSV).
- [ ] 2. Get the ids (including handles) of works with 10+ creators by running the task introduced in https://github.com/osulp/Scholars-Archive/pull/1814 to find all those works that have the type mismatch issue
- [ ] 3. Create a subset of a cleaned up csv file `dspace_creator_order.csv` that contains works with the correct characters and works with 10+ creators (include even if the symbols are correct to address the issue that was fixed by https://github.com/osulp/Scholars-Archive/pull/1774 and https://github.com/osulp/Scholars-Archive/pull/1776)
- [ ] 4. Tweak task `scholars_archive:migrate_ordered_metadata_with_handles` or add a new one to force or skip the part that checks that a work has already been migrated to be able to run the migrator again.
- [ ] 5. Run task with the new subset of works to address both the order and special chars

**Comment by luisgreg99** [comment]
For (1) I found the original dspace_creator_order.csv that @zhang4952 posted in the past https://osulets.slack.com/archives/C03G2FZ9Q/p1534351275000100 Doing a `diff` I got a list of creators that didn't match those in the server `ordered_attributes_migrations/dspace_creator_order.csv` I made a list in [Handles with unclean creators](https://docs.google.com/spreadsheets/d/1ohRjUxpTewPrqxPSjGE82kx4QKF95yfP7elBbb-F1D4/edit?usp=sharing)

**Comment by luisgreg99** [comment]
For (2) I updated the task `scholars_archive:migrated_works_10_or_more_creator` and got an updated list, now with handles. I added the handles in a new tab [handles with 10 or more creators](https://docs.google.com/spreadsheets/d/1ohRjUxpTewPrqxPSjGE82kx4QKF95yfP7elBbb-F1D4/edit#gid=1095165139). Since some handles might have both order and symbol issues, the list could be reduced for (3). I will work on a task next to use a combined list for (3) to address (4).

**Comment by luisgreg99** [comment]
For (3), ran `bundle exec rake scholars_archive:get_json_of_handles_to_be_fixed_excluding_works_manually_fixed` and then did an analysis and it looks like `458` works will need to be fixed. `432` works were already fixed! @simholt nice work! It looks like we don't have to worry about these in the final CSV for (4)

**Comment by luisgreg99** [comment]
Update for (3)

**Results:**

In summary, we have four groups of handles with distinct properties.

- Group **X**: Already fixed by @simholt
- Group **Y**: Unknown char ‘?’ issue
- Group **Z**: Works with 10+ creators issue
- Group **W**: Works with creators updated before or after ordered metadata migration that also have **Y** and/or **Z** issues

Venn diagram to help visualize special cases:

![image](https://user-images.githubusercontent.com/3486120/54229911-7ba0f100-44c2-11e9-9268-0beb75370a34.png)

**Comment by luisgreg99** [comment]
**Fixes**

For the **automated fix**, we would need 2 subsets to use as inputs to force migration:

Handles to fix the unknown char issue for the first run:

```
R1 = Y - (X + W)
```
Count: `455`
Spreadsheet: [R1 handles](https://docs.google.com/spreadsheets/d/1FRzgMpvlY27ylm1u3XdnRobvO5jNo64R2eu4x0kjgZw/edit#gid=1266860208)

Handles to fix the 10+ creators issue for the second run:
```
R2 = Z - (X + Y + W)
```
Count: `527`
Spreadsheet: [R2 handles](https://docs.google.com/spreadsheets/d/1FRzgMpvlY27ylm1u3XdnRobvO5jNo64R2eu4x0kjgZw/edit#gid=307385393)

```
Manual = W - X
```
Count: `44`
Spreadsheet: [Manual](https://docs.google.com/spreadsheets/d/1FRzgMpvlY27ylm1u3XdnRobvO5jNo64R2eu4x0kjgZw/edit#gid=0)

For the **manual fix**, I propose Group W (minus X) since a fix can be hard to predict. Automating a fix for changes introduced after or before migration might not be worth the effort since it's a small group.

**Comment by luisgreg99** [comment]
For (4) I prepared the following tasks:
```
bundle exec rake scholars_archive:migrate_dspace_creator_char_cleanup
bundle exec rake scholars_archive:migrate_dspace_creator_order_cleanup
```

**Comment by luisgreg99** [comment]
R1 task finished successfully.
```
# R1
bundle exec rake scholars_archive:migrate_dspace_creator_char_cleanup
```

Now running R2:
```
# R2
bundle exec rake scholars_archive:migrate_dspace_creator_order_cleanup
```

**Comment by luisgreg99** [comment]
R2 task `scholars_archive:migrate_dspace_creator_order_cleanup` finished successfully.

**Comment by luisgreg99** [comment]
@simholt I checked the logs and didn’t find any issues with the previous tasks (R1 and R2). I ran again one of my first tasks `scholars_archive:get_json_of_handles_to_be_fixed_excluding_works_manually_fixed` to double check that the unknown char was fixed, so I can confirm that the cleanup tasks worked as expected. I also checked the ones listed in your main ticket.  If you would like to double check, let me know if you find any issues

**Comment by simholt** [comment]
Completed the 40+ manual corrections.

**Comment by luisgreg99** [comment]
@simholt After running `get_all_handles_to_be_fixed_for_x` and `find_creators_with_additional_changes_w3`, I found 1 work (added to [Manual](https://docs.google.com/spreadsheets/d/1FRzgMpvlY27ylm1u3XdnRobvO5jNo64R2eu4x0kjgZw/edit#gid=0) tab) that would need to be fixed manually and 128 works that we can fix automatically (R3). 

I've also updated the spreadsheet in tab for [R3 run](https://docs.google.com/spreadsheets/d/1FRzgMpvlY27ylm1u3XdnRobvO5jNo64R2eu4x0kjgZw/edit#gid=1479520724)

**Comment by luisgreg99** [comment]
Currently running `bundle exec rake scholars_archive:migrate_dspace_creator_member_cleanup` to cleanup child members of handles in [R3 list](https://docs.google.com/spreadsheets/d/1FRzgMpvlY27ylm1u3XdnRobvO5jNo64R2eu4x0kjgZw/edit#gid=1479520724)

**Comment by luisgreg99** [comment]
R3 task scholars_archive:migrate_dspace_creator_member_cleanup finished successfully.

**Comment by simholt** [comment]
Corrected manual member works.

**Comment by luisgreg99** [comment]
@simholt I ran the task `bundle exec rake scholars_archive:qa_for_unclean_creators` and didn't find any additional creators to be fixed. I think we have covered every case with this issue for creators.

**Comment by simholt** [comment]
ALL DONE
