### ISSUE TITLE
allow depositor to see work even if visibility is restricted

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1878]
### Descriptive summary

Depositors in SA@OSU should be able to see their own deposited work, even if the visibility of the work is set to Private or OSU. 

### Expected behavior
When the Depositor is authenticated, they should be able to see the work showpage for any of their deposited works, regardless of visibility.

### Actual behavior
Depositor is refused access to their work if visibility is set to private.

**Comment by simholt** [comment]
@straleyb 

Many thanks to @DeadCatLady for helping test this one.
***
The Private test upload to **Default** allowed the user to view AND edit the record. We don't want them to be able to edit anything, just view their record and download the file.
![imageedit](https://user-images.githubusercontent.com/33705514/75929858-48b7e180-5e26-11ea-862f-c4bbb7b4cf9e.png)

***
The Private test upload to **Undergrad Thesis or Project** allowed the user to view the record -- no editing allowed, so that's good. However, it skipped the review queue. It shows up under All Works as Pending Review but is not listed in the Review Submissions list on either tab.

![image](https://user-images.githubusercontent.com/33705514/75929787-2c1ba980-5e26-11ea-80b7-16891b77070a.png)
<br>
![Screen_Shot_2020-03-04_at_2_44_07_PM](https://user-images.githubusercontent.com/33705514/75930101-c4b22980-5e26-11ea-84c8-e8567e311efa.png)

**Comment by straleyb** [comment]
@simholt So I ran a test on staging regarding the first ingest @DeadCatLady did. 
<img width="1545" alt="Screen Shot 2020-03-05 at 12 20 56 PM" src="https://user-images.githubusercontent.com/6424683/76022366-d86b9780-5edb-11ea-9386-fa4dcdd9b37a.png">

I removed myself as an admin just to be a normal user. Id like to know the steps that she went through to see where the disconnect was. Note: If you are a manager for an admin set, the person who ingested can still edit a work. 

Ill test the second case as well and update here.

**Comment by straleyb** [comment]
So I got this first part working. For some reason, the edit users werent updating properly for the "Default" admin set. This should be funtioning as expected.

**Comment by straleyb** [comment]
For the second one here. The All Works tab only shows up if you are an admin. So that will show you all works including private and unreviewed works. If you are a non-admin user, it only shows up as "managed works". The discovery of the private work as a non-admin user is as expected, it doesn't show up. Is this how we would like things to work? 

If we need to walk through these together and talk about them, we can do that too. Maybe there is some pieces missing regarding what managers vs admin can see.

**Comment by simholt** [comment]
> For the second one here. The All Works tab only shows up if you are an admin. So that will show you all works including private and unreviewed works. If you are a non-admin user, it only shows up as "managed works". The discovery of the private work as a non-admin user is as expected, it doesn't show up. Is this how we would like things to work?

Yes, that's good. The key here is for items to show in the appropriate queue.

**Comment by simholt** [comment]
Christa submitted another undergrad thesis and it still didn't show up in the review queue, only in Works with the review status:

<img width="834" alt="Screen Shot 2020-03-09 at 10 25 31 AM" src="https://user-images.githubusercontent.com/33705514/76240432-77500680-61f0-11ea-8572-b1ffe54eec0b.png">

<img width="858" alt="Screen Shot 2020-03-09 at 10 25 07 AM" src="https://user-images.githubusercontent.com/33705514/76240434-7919ca00-61f0-11ea-8ba7-1b015468322b.png">

**Comment by luisgreg99** [comment]
I double checked the visibility for private works in the queue and found these cases:

Private work in "Undergrad Thesis or Project" doesn't show up in the "Under Review" tab:
a) **non-admin** and **not-a-manager** for "Undergrad Thesis or Project"
b) **admin** and **not-a-manager** for "Undergrad Thesis or Project"

Private work in "Default" doesn't show up in the "Published" tab:
c) **non-admin** and **not-a-manager** for "Default"
d) **admin** and **not-a-manager** for "Default"

It seems like the only ones with inconsistencies in the queue are (b) and (d). I suspect these were the cases that Sarah experienced in https://github.com/osulp/Scholars-Archive/issues/1878#issuecomment-594909230 and https://github.com/osulp/Scholars-Archive/issues/1878#issuecomment-596669233.

When I removed myself from the manager role for one of these project types, while still being an admin user, I was unable to see the private work in the review queue. It looks like the manager role is taking precedence over the admin role for visibility in the queue.

**Comment by luisgreg99** [comment]
Closing -- this issue appears to have been fixed already by https://github.com/osulp/Scholars-Archive/pull/2106 

After discussion with Sarah, we are creating a new issue https://github.com/osulp/Scholars-Archive/issues/2129 to address the visibility concerns regarding the review queue for users with the admin role.
