### ISSUE TITLE
Exclude thumbnail files from Google Analytics tracking via Downloads Controller

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#1889]
### Descriptive summary

At least some calls to display thumbnails pass them through the Downloads controller, which triggers our Google Analytics event with the staccato tracker. These don't need to be tracked this way. 

![image](https://user-images.githubusercontent.com/2293544/59138465-2437e300-8942-11e9-8d56-12083f1662b9.png)

### Expected behavior

Thumbnails are not tracked separately in Google Analytics.

### Actual behavior

Thumbnails are tracked separately in Google Analytics.

**Comment by carakey** [comment]
Any suggestions how to QA this ticket? 

I am able to go to GA4 for Staging and confirm that views/downloads are being tracked. A search for "thumbnail" in the GA Pages and Screens tab doesn't give any results, but it doesn't in GA4 for Production either. I'm not sure how else to test. 

As background, "thumbnail downloads" were visible as separate line items in GA3 and, while included in total download counts for an item, they could be filtered out. Since the GA upgrade, we haven't been able to tell whether are included or not in the counts.

**Comment by CGillen** [comment]
See all GA traffic no longer references `/downloads/<pid>?file=thumbnail`.
QA Pass
