### ISSUE TITLE
Time zone set to GMT/UTC

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#2213]
### Descriptive summary

Added a new file to a record around 4pm on Mar 10th and the Date Uploaded (at the bottom of the show page) listed the date as Mar 11th. I made a test deposit this morning and the record for an item submitted at 11:05am lists "system_create_dtsi":"2021-03-11T19:05:20Z"

Item: xw42ng22m

This is important for general accuracy and especially for ETDs because submission dates determine when and if grad students meet graduation deadlines. 

### Expected behavior
The date a file is uploaded corresponds with PST. It looks like it is set at GMT/UTC time right now.

### Actual behavior
Is not PST.

### Steps to reproduce the behavior

1. Deposit an item.
2. Check the system_create date/time

**Comment by CGillen** [comment]
Turns out Solr only likes date/time in UTC and has been indexing this way the whole time. From the Solr docs: 
```
Note that no time zone can be specified; the String representations of dates is always expressed in Coordinated Universal Time (UTC).
```
 I checked some production solr documents that never made it through reindexing and they followed the UTC format.
I ended up making it so that anything that tries to receive the date indirectly (not knowing to look up exactly `date_uploaded_dtsi`) will receive a date/time in PST/PDT
```
sd.title
=> ["hello_world.pdf"]
irb(main):007:0> sd['date_uploaded_dtsi']
=> "2020-07-30T02:39:00Z"
```
<img width="345" alt="image" src="https://user-images.githubusercontent.com/11052958/110997349-1fcc0580-8332-11eb-9a42-ff803688fa4c.png">
