### ISSUE TITLE
OAI response lacking metadata

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#2248]
### Descriptive summary

#2231 got the OAI endpoing mostly working again.

For https://ir.library.oregonstate.edu/catalog/oai?verb=ListSets
Drop `isPartOf_ssim:` from the OAI set setSpec. That should just be an identifier and doesn't need the Solr field name. 
This should also resolve the error when trying to view Records with a given set:
https://ir.library.oregonstate.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc&set=isPartOf_ssim:2b88qc16g  (gives `The request includes illegal arguments, is missing required arguments, includes a repeated argument, or values for arguments have an illegal syntax.`)

Most metadata fields are not being included in ListRecords for `oai_dc` format: https://ir.library.oregonstate.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc 

We're also missing the `oai_qdc` Qualified Dublin Core format being enabled, which has more configuration for response fields done here: https://github.com/osulp/Scholars-Archive/blob/master/lib/scholars_archive/document/qualified_dublin_core.rb 

### Related work

#2231

**Comment by CGillen** [comment]
After discussing with Ryan W. we determined this three part issue is a little off. The OAI setSpecs previously included `isPartOf_ssim` but now we don't want that. We think there isn't any other harvesters besides our own right now (for OregonExplorer), and any possible other ones would have already been broken anyways.

The metadata fields were working but there was some confusion with the first set of responses being collections. I've opened a new ticket to remove collections from the OAI response: #2254 

Our code for `oai_qdc` is identical to `oai_dc` and doesn't appear to have been written to extend `blacklight_oai_provider` but instead part of blacklight that provides people with different export formats for `/catalog` and is supposed to provide the same formats for individual works. Blacklight doesn't seem to be able to do this, because Hyrax has chosen to skip Blacklight for the work show pages, which is how BL hooks those exports.
