### ISSUE TITLE
Update BitTorrent Guide to reference another supportable client

### ISSUE THREAD

**Issue by decimalator** [osulp/Scholars-Archive#2374]
### Descriptive summary

uTorrent is considered to be Ad-ware and is blocked by Microsoft Defender. This effectively prevents any OSU staff/faculty (and some students?) from being able to use it on University computers. uTorrent is the only bittorrent client that we have documentation for.

- Replace uTorrent docs with qbittorrent https://library.oregonstate.edu/bittorrent-guide
- Other clients?

**Comment by mellinma** [comment]
Ryan what do we need to do on the infrastructure end?  I just want to make sure that I update the webpage when we need to do so.

**Comment by decimalator** [comment]
Nothing on the infra end, BitTorrent is peer-to-peer. We run Transmission (https://transmissionbt.com/) as our "BitTorrent service", any client should be able to talk to it. We just need similar instructions for other BitTorrent clients.

**Comment by carakey** [comment]
Clara and I updated the BitTorrent Guide at https://library.oregonstate.edu/bittorrent-guide to recommend qBitTorrent. We also updated the language used in the instructions included on the datasets in SA so that they no longer recommend a particular client and Clara replaced those instruction files.
