### ISSUE TITLE
Author Profiles should offer links to external profiles

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#258]
Such as: ResearchGate, Mendeley, Google Scholar, ORCID, etc.

**Comment by vantuyls** [comment]
Add Google Scholar Profiles as a starting point. 

@mwillihooper in the longer term, what types of external profiles would we like to see users able to link their SA profile to?

**Comment by mwillihooper** [comment]
@vantuyls : Do we need to parse them all out, or can we have a generic option as well? (for example, if they want to link to their lab/ homepage). RG may eventually be surpassed by another corporate networking tool, so we probably want some flexibility. Twitter seems common. ORCID is definitely the main one--are we still looking to use it to auto-populate author info/force them to sign up for ORCID when they create an author profile?

**Comment by mwillihooper** [comment]
Also LinkedIn.

**Comment by vantuyls** [comment]
right. it'd probably best to specify which social networks they're linking out to. As the idea of Author Profiles becomes more robust, we'll have more flexibility around things like linking out to arbitrary websites like lab pages etc.

**Comment by mwillihooper** [comment]
I agree about having specific fields for popular social networks. Since "popular" is a moving target, those will likely need to change over time. 

There is also a distinction between social media accounts, researcher profiles (ImpactStory, GoogleScholar), and disambiguation registries (ORCID and [ResearcherID](http://www.researcherid.com/Home.action?returnCode=ROUTER.Unauthorized&SrcApp=CR&Init=Yes)). 

 If we don't want to list a dozen different profiles, one thing to do is think about why we're including this. ORCID, ResearcherID, and Google Scholar are helpful for identifying someone's work. 

Users may want to highlight LinkedIn, Twitter, ResearchGate, Facebook because of opportunity to promote/connect, but I don't think we're currently looking at those as sources of pub/CV information.

**Comment by mwillihooper** [comment]
[This article](http://www.nature.com/news/online-collaboration-scientists-and-the-social-network-1.15711) is three years old, but summarizes a Nature survey on scholars and social media use. The top networks by reported use: RG (by far the largest), LinkedIn, Facebook, Twitter, Academia.edu, and Mendeley. I would include all, or possibly drop off Academia.edu and Mendeley if you don't want that many. I think ORCID and ResearcerID are also important for disambiguation. Let me know if you need more info/feedback on this!

**Comment by vantuyls** [comment]
this functions as designed in Hyrax 2.0. Further enhancement should wait for use cases to emerge.
