### ISSUE TITLE
itemtype attribute in Rights show fields partial should be https://schema.org/license

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#306]
https://github.com/osulp/Scholars-Archive/blob/master/app/views/records/show_fields/_rights.html.erb

itemtype value should be `https://schema.org/license`

**Comment by straleyb** [comment]
Currently, rights show does not use itemtype in the html. Do we still want this? Another question I have is do we still want to use `https://schema.org/license` since there is also a license field. @wickr What do you think?

https://github.com/projecthydra-labs/hyrax/blob/c2e6f0229565a64a4dce1d32d1e763b128b9dc7e/app/views/records/show_fields/_rights.html.erb

Page that renders the rights on the show page.

**Comment by straleyb** [comment]
https://github.com/projecthydra-labs/hyrax/issues/808 Hyrax ticket
