### ISSUE TITLE
[Analytics] Direct-link file download to naturally work with Sufia stats

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#309]
update downloads_controller.rb set category, action, and label to match the format that Sufia expects for the stats page to draw out the counts from the GA. 

category = "Files"
action = "Downloaded"
label = "sufia:#{params[:id]}"

**Comment by zhang4952** [comment]
related #274. branch restored at https://github.com/osulp/Scholars-Archive/commit/68be5f141566cdca56064c201dd87fb6e7c20c37

**Comment by zhang4952** [comment]
For the discussion of a 'good' solution, here is the Staccato tracker.rb: https://github.com/tpitale/staccato/blob/c77484d1ac01ab93559ab030611b3024db3f6c76/lib/staccato/tracker.rb that can be useful.

**Comment by zhang4952** [comment]
Per the discussion at the check-in on July 31:
- the issue is a visit like `http://lib-saapp1.library.oregonstate.edu/downloads/6d56zw708?locale=en` won't trigger GA download event because it does not render a HTML page
- current in Hyrax, a download is tracked in GA only when a user clicks the 'download' button in the file page (like the JS: https://github.com/samvera/hyrax/blob/1e504c200fd9c39120f514ac33cd42cd843de9fa/app/assets/javascripts/hyrax/ga_events.js)
- the solution will be adding a method to the download_controller.rb: 1. looking for pattern in the in-coming urls (e.g., /downloads). 2. find the correct file_id/work_id, create the GA event and push it to Google. 3. Staccato gem provides several useful methods: https://github.com/tpitale/staccato/blob/c77484d1ac01ab93559ab030611b3024db3f6c76/lib/staccato/tracker.rb

**Comment by wickr** [comment]
Current plan is to disable Hyrax Downloaded button event triggered by Javascript, and track all downloads through the downloads controller and send those stats to GA in the same form that Hyrax expects.
