### ISSUE TITLE
New Users email not guaranteed to come from CAS

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#316]
For instance, when Greg logs in, his username luisramg is added to the users table but no email is set. Could be relate to CAS reply?

**Comment by revgum** [comment]
Because CAS isn't necessarily guaranteed to be feeding an email address back, we need to set a "default & unique" email address before creating the user. When we detect that the users email is still configured as the default, redirect them to their profile page to have them update their email address.

**Comment by revgum** [comment]
If CAS returns an invalid user (no email address), allow the user to punch one in manually during registration.

**Comment by luisgreg99** [comment]
I don't actually have this issue anymore with my CAS authentication. It looks like CAS now ties the session with the user's primary email address instead of the preferred address, which was tied to the user's decision to filter or hide it in the directory profile settings. I think CAS now assures that an email is returned for ONID accounts regardless of the profile settings in the directory.

In @vantuyls email regarding CAS questions, I think only DINO accounts http://onid.oregonstate.edu/docs/technical/dino.shtml are not tied to a primary address, so I believe CAS won't return emails for this type of accounts.

**Comment by vantuyls** [comment]
okay, close this, then, if you're fairly sure this is resolved.

**Comment by luisgreg99** [comment]
@vantuyls sounds good, I tested it on my local, and CAS is working as expected. I also tested it with @revgum at some point in the past in the staging server when I got my account there. If I remember correctly, it worked there too since I now see the correct email in my profile.
