### ISSUE TITLE
[S6 -> S7 port] Monthly download and pageview table

### ISSUE THREAD

**Issue by straleyb** [osulp/Scholars-Archive#374]
We created a table which displayed the monthly downloads and pageviews of an item. We need to move this over to our sufia 7 instance.

**Comment by zhang4952** [comment]
The "Nomethoderror for sufia__pageview" that block this ticket for days is identified as because 'eager_load' in environment is set to 'true' only for production so pageview and download model do not load into memory and extend legato. Please see notes from Josh in below for details. The better solution could be an initializer for legato/analytics that load the pageview model by force.

I’ve been digging into our analytics issue with @zhanghu and the nomethoderror for sufia__pageviews. The underlying issue was that `eager_load=false` for everything but production.. so our staging and development environments weren’t eager loading `models/sufia/pageview.rb` and `models/sufia/download.rb`.. so these classes didn’t wire up properly to the `Legatto::ProfileMethods.add_profile_method` which eventually creates the sufia__pageviews method dynamically. When we set eager_load to true for development and staging environments, everything works as expected. My question is, maybe the loading of Google Analytics related models like pageview and download could be loaded into the environment through a new Legato initializer? This seems a little bit more clear of an approach.. what do you all think? https://github.com/projecthydra/sufia/blob/47d426fd4956664f69545779a43b8404f8edf490/lib/sufia/engine.rb and https://github.com/tpitale/legato/blob/e3af3cfd5dba8e2f61266d9c4758997c4632304b/lib/legato/profile_methods.rb

[12:01]  
(The comment in the engine.rb says that eager_loading would work for development, but it isn’t)
