### ISSUE TITLE
Create Deposit Agreement Text

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#40]

**Comment by zhang4952** [comment]
In order for ScholarsArchive@OSU to reproduce, translate and distribute your submission worldwide, you must agree to the following terms.

Grant the standard distribution license by selecting 'I Grant the License'; and then click 'Complete Submission'.

You retain all of your ownership rights in all materials submitted to ScholarsArchive@OSU (“Your Material”). But by submitting Your Material to ScholarsArchive@OSU, you hereby grant OSU a worldwide, non-exclusive, irrevocable, royalty-free right to reproduce and distribute Your Material in any format or medium for non-commercial, academic purposes only. You do not give up the right to submit the work to publishers or other repositories. OSU will clearly identify your name(s) as the author(s) or owner(s) of the material. You represent and warrant that: i) Your Material does not infringe or violate someone else’s rights or otherwise violate the law, and ii) you have authority to grant OSU all of the rights under this license.

If you have questions regarding this license please contact the system administrators.


Distribution license:
 I Grant the License
