### ISSUE TITLE
Implement Questioning Authority for Local Authorities and activate URI fields

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#535]

**Comment by vantuyls** [comment]
Need to suss out the details (more granular issues) for this implementation

**Comment by straleyb** [comment]
Languages and Geolocations but not subject. @vantuyls Is this correct for ALL the URI fields in SA?

**Comment by vantuyls** [comment]
No, we also need Academic Units, License, Rights Statement, Funding Body, Conference Location. The Metadata Application Profile has an "Expected Type" column that indicates the fields that require a URI.

**Comment by vantuyls** [comment]
@straleyb @wickr are we resolved on this?

**Comment by revgum** [comment]
"Academic Affiliation"
"Other Affiliation"
"Language"
"Rights Statement"
"License"
"Location"
"Funding Body"

Each of these fields need to have the labels indexed and faceted (instead of the URI faceted)

For the remote hosted (Academic Units related fields and Location) the labels needs to be fetched on save.
