### ISSUE TITLE
Use OSU graphical elements for placeholder icons

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#849]
Default Hyrax icons should be replaced with OSU graphical icons to match branding needs.

**Comment by vantuyls** [comment]
if someone could give me a list/copy of all of the icons hyrax is trying to use, i can find the OSU icon to replace it with

**Comment by vantuyls** [comment]
icons are located here on hyrax: 

https://github.com/samvera/hyrax/tree/master/app/assets/images

**Comment by vantuyls** [comment]
collection.png:
![collection](https://user-images.githubusercontent.com/9534576/29844952-ee95708e-8cc5-11e7-8cf2-5cfa0c9b3d99.png)

audio.png:
![audio](https://user-images.githubusercontent.com/9534576/29848455-9459661a-8cd5-11e7-922c-f259705c55b0.png)


default.png:
![default](https://user-images.githubusercontent.com/9534576/29844958-f3362a70-8cc5-11e7-81eb-99cf90c330b0.png)

**Comment by wickr** [comment]
It may not be a problem if these are always on a white background, but for audio.png, it's mostly transparent except for 2 white rectangles that are in the areas of the line gaps. If you do "open image in new tab" you should be able to see it.

Collection and Default may be too small too, and since they're PNGs they won't scale well. Current ones are 442 px square vs. 150 px square.

**Comment by vantuyls** [comment]
nope, thats my crummy design work. i'll fix the audio. will look at larger icons.

**Comment by vantuyls** [comment]
updated
