### ISSUE TITLE
SA is duplicating files

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#914]
when depositing a work, something funky is going on with characterization that is causing the file to get re-attached multiple times, thus duplicating the file on the work.

**Comment by revgum** [comment]
![screen shot 2017-09-14 at 9 22 58 am](https://user-images.githubusercontent.com/32885/30443892-06984478-9936-11e7-9089-415e708e1b73.png)

Seems that characterization is failing using `fits` and attaches the fileset to the work before the failure happens.. Sidekiq restarts periodically, and continues to attach new filesets

**Comment by luisgreg99** [comment]
I looked more into the issue and found a few things that we can do regarding this issue. There are some updates that are available now in the latest hyrax pre-release (2.0.0.beta3) particularly about file sets that could resolve the duplicate bug. These are some steps to consider for this issue:

- [ ] update hyrax gem to latest available: hyrax (2.0.0.beta3) pre-release
- [ ] update fits to 1.0.5 [known to be good according to the hyrax readme] current version being used in staging is 0.8.5
- [ ] test staging with sample file to verify if we still have the issue
- [ ] if behavior persists, we could tweak Sidekiq to run only once to prevent duplicates? we can discuss this option if needed in the end

**Comment by luisgreg99** [comment]
After taking a closer look at the logs and the Sidekiq issues queue (mainly https://github.com/mperham/sidekiq/issues/972), it looks like we can resolve the fits error just by restarting the main Sidekiq process.
 
I found that the error `Errno::ENOENT: No such file or directory @ rb_sysopen - /data0/hydra/releases/20170801150642/config/authorities/rights_statements.yml` was raised because of a non-existing release folder `/20170801150642/`. This folder was removed automatically when the app reached 5 newer releases. That is the limit of versions that we currently have in place for the `releases` folder (see https://github.com/osulp/Scholars-Archive/blob/master/config/deploy.rb#L39). 

This is most likely the same reason why we were getting the fits error `shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory` that ended up causing duplicate filesets in the work.
 
I think we should configure our deploy process to also restart Sidekiq when publishing updates to the codebase to make sure that it actually comes from the latest release directory.
