### ISSUE TITLE
Change Other Affiliation to use local YAML file with URIs

### ISSUE THREAD

**Issue by wickr** [osulp/Scholars-Archive#958]
Change Other Affiliation to use local YAML file with URIs, in order to give a dropdown list on the form.
Needs an Other option for new submissions.

Use the 'Nonacademic Units' tab on the DSpace Community and Collections - Admin Set and Affiliation Crosswalk doc.

**Comment by luisgreg99** [comment]
@vantuyls @wickr given that `other_affiliation` is a multi-value field, should we also have multiple "Other" entries for this field? 

I'm thinking that if we want a single entry for `other_affiliation`, we can have a button to trigger the "Other" input at the end of the field (see mockup). Also, since we collect both the input text and the property name in the database, it's possible to store multiple "Other" entries for the `other_affiliation` field if needed. 

Thinking about the interface, I have the following mockups for both single and multiple value approaches:

![other_affiliation_mockup](https://user-images.githubusercontent.com/3486120/31556985-f92edd24-affb-11e7-81a9-d3679643a435.png)

**Comment by wickr** [comment]
I think Multiple works best, it may not be common but there may be cases where it's needed. So the 2nd option works, and is closest to what we have now.
