### ISSUE TITLE
Commencement Year index

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#970]
Looks like dates are incorrectly parsed or indexed

<img width="350" alt="screen shot 2017-10-23 at 8 37 55 am" src="https://user-images.githubusercontent.com/32885/31898315-b3b64898-b7cd-11e7-9288-0468437d1f8a.png">

**Comment by luisgreg99** [comment]
It turns out that the ajax call that was used to calculate the boundaries in blacklight_range_limit were broken by two works with the wrong format in `graduation_year`:

![image](https://user-images.githubusercontent.com/3486120/31912279-348eb7d2-b7f8-11e7-9cdf-342f1a658e37.png)

If we inspect the url used in the ajax call, we can see the two values being used in `range_start` and `range_end` appeared to break the response:

`/catalog/range_limit?commit=Limit&locale=en&q=&range_end=June+17%2C+2017&range_field=graduation_year_sim&range_start=05-31-2017&search_field=all_fields&utf8=%E2%9C%93`

After doing a solr query for these two values `June+17%2C+2017` and `05-31-2017`, there were only two works these values. @zhang4952 updated these two works with the proper values for commencement year, and that seemed to fix the issue:

![image](https://user-images.githubusercontent.com/3486120/31912565-27fedaaa-b7f9-11e7-8ad0-277cbf7055b9.png)
